version: 2.1

executors:
  ruby-docker:


jobs:
  heroku-18:
    # need to use machine executor for volume mounting in docker
    # https://circleci.com/docs/2.0/executor-types/#using-machine
    # can use docker cp instead
    # https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
    machine: true
    environment:
      STACK: heroku-18
      VERSION: 2.5.3
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -f dockerfiles/Dockerfile.$STACK -t hone/ruby-builder:$STACK .
      - run:
          name: Build Ruby
          command: bash rubies/$STACK/ruby-$VERSION.sh
      - store_artifacts:
          path: builds

workflows:
  version: 2.1
  heroku-18:
    jobs:
      - heroku-18
