version: 2.1

# reusable commands
commands:
  build-docker-image:
    description: "Build Docker Image"
    parameters:
      stack:
        type: string
    steps:
      - run:
          name: Build Docker Image
          command: docker build -f dockerfiles/Dockerfile.<< parameters.stack >> -t hone/ruby-builder:<< parameters.stack >> .

  build-ruby:
    description: "Build Ruby"
    parameters:
      stack:
        type: string
      version:
        type: string
    steps:
      - run:
          name: Build Ruby
          command: bash rubies/<< parameters.stack >>/ruby-<< parameters.version >>.sh

jobs:
  build:
    # need to use machine executor for volume mounting in docker
    # https://circleci.com/docs/2.0/executor-types/#using-machine
    # can use docker cp instead
    # https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
    machine: true
    parameters:
      stack:
        type: string
      version:
        type: string
    steps:
      - checkout
      - build-docker-image:
          stack: << parameters.stack >>
      - build-ruby:
          stack: << parameters.stack >>
          version: << parameters.version >>
      - store_artifacts:
          path: builds

workflows:
  version: 2.1
  heroku-18:
    jobs:
      - build:
          stack: "heroku-18"
          version: "2.5.3"
  heroku-16:
    jobs:
      - build:
          stack: "heroku-16"
          version: "2.5.3"
  cedar-14:
    jobs:
      - build:
          stack: "cedar-14"
          version: "2.5.3"
